openapi: 3.0.0
info:
  title: Driver Route Assignment System
  version: 2.0.0
  description: Complete driver route assignment system with date-aware optimization
servers:
  - url: https://5ead40e0-94db-4e13-b32d-b48000528c25-00-eecmz5446ewu.picard.replit.dev
paths:
  /api/ortools/drivers:
    get:
      summary: Get drivers for optimization with date-aware hours
      parameters:
        - name: year
          in: query
          schema:
            type: integer
          description: Year for hour calculations (e.g., 2025)
        - name: month
          in: query
          schema:
            type: integer
          description: Month for hour calculations (1-12)
      responses:
        '200':
          description: List of drivers with available hours
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    available_hours:
                      type: number

  /api/ortools/routes:
    get:
      summary: Get available routes
      responses:
        '200':
          description: List of routes
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    hours:
                      type: number

  /api/ortools/optimize:
    post:
      summary: Optimize driver-route assignments using OR-Tools
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                drivers:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      available_hours:
                        type: number
                    required: [name, available_hours]
                routes:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      hours:
                        type: number
                    required: [name, hours]
              required: [drivers, routes]
      responses:
        '200':
          description: Optimized assignments
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [optimal, infeasible, error]
                  assignments:
                    type: array
                    items:
                      type: object
                      properties:
                        driver_name:
                          type: string
                        route_name:
                          type: string
                        route_hours:
                          type: number
                  driver_status:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        assigned_route:
                          type: string
                        assigned_hours:
                          type: number
                        remaining_hours:
                          type: number
                  unassigned_routes:
                    type: array
                    items:
                      type: string
                  statistics:
                    type: object
                    properties:
                      total_routes:
                        type: integer
                      routes_assigned:
                        type: integer
                      routes_unassigned:
                        type: integer
                      total_hours_assigned:
                        type: number
                      drivers_working:
                        type: integer
                      drivers_available:
                        type: integer
                  objective_value:
                    type: number

  /api/ortools/apply:
    post:
      summary: Apply optimization results to database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                assignments:
                  type: array
                  items:
                    type: object
                    properties:
                      driver_name:
                        type: string
                      route_name:
                        type: string
                      route_hours:
                        type: number
                assigned_date:
                  type: string
                  format: date
                  description: Date for assignments (YYYY-MM-DD)
              required: [assignments, assigned_date]
      responses:
        '200':
          description: Assignments applied successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  assignments_created:
                    type: integer

  /api/gpt/optimize-day:
    post:
      summary: Complete day optimization workflow (analyze, optimize, apply)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                selectedDate:
                  type: string
                  format: date
                  description: Date to optimize (YYYY-MM-DD)
                additionalRoutes:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      hours:
                        type: number
                  description: Optional additional routes to include
                excludeDrivers:
                  type: array
                  items:
                    type: string
                  description: Driver names to exclude from optimization
                priorityRoutes:
                  type: array
                  items:
                    type: string
                  description: Route names that must be assigned if possible
              required: [selectedDate]
      responses:
        '200':
          description: Complete optimization results
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  date:
                    type: string
                  optimization:
                    type: object
                    properties:
                      status:
                        type: string
                        enum: [optimal, infeasible, error]
                      assignments:
                        type: array
                        items:
                          type: object
                          properties:
                            driverName:
                              type: string
                            routeName:
                              type: string
                            routeHours:
                              type: number
                            driverRemainingHours:
                              type: number
                      statistics:
                        type: object
                        properties:
                          totalRoutes:
                            type: integer
                          routesAssigned:
                            type: integer
                          routesUnassigned:
                            type: integer
                          driversWorking:
                            type: integer
                          driversAvailable:
                            type: integer
                          totalHoursAssigned:
                            type: number
                          averageHoursPerDriver:
                            type: number
                      unassignedRoutes:
                        type: array
                        items:
                          type: string
                      recommendations:
                        type: object
                        properties:
                          message:
                            type: string
                          suggestedActions:
                            type: array
                            items:
                              type: string
                  databaseUpdated:
                    type: boolean
                  message:
                    type: string

  /api/gpt/monthly-balance/{year}/{month}:
    get:
      summary: Get monthly balance report for all drivers
      parameters:
        - name: year
          in: path
          required: true
          schema:
            type: integer
        - name: month
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Monthly balance report
          content:
            application/json:
              schema:
                type: object
                properties:
                  drivers:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        code:
                          type: string
                        monthlyHoursTotal:
                          type: number
                        monthlyHoursUsed:
                          type: number
                        monthlyHoursRemaining:
                          type: number
                        utilizationPercentage:
                          type: number
                        status:
                          type: string
                          enum: [critical, low, normal, optimal]
                  summary:
                    type: object
                    properties:
                      totalDrivers:
                        type: integer
                      averageUtilization:
                        type: number
                      criticalDrivers:
                        type: integer
                      lowHoursDrivers:
                        type: integer
                      optimalDrivers:
                        type: integer
                      totalMonthlyHours:
                        type: number
                      totalHoursUsed:
                        type: number
                      totalHoursRemaining:
                        type: number