openapi: 3.0.0
info:
  title: get_apidrivers
  version: 1.0.0
servers:
  - url: https://5ead40e0-94db-4e13-b32d-b48000528c25-00-eecmz5446ewu.picard.replit.dev
paths:
  /api/ortools/drivers:
    get:
      summary: Get all drivers with remaining monthly hours
      responses:
        '200':
          description: List of drivers with available hours
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    name:
                      type: string
                    available_hours:
                      type: number
                  required: [name, available_hours]